// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyddRIbbTPIgt2VS72FGUwb-Oi0KFWmYQ',
    appId: '1:992713183621:web:ef01a1e80c2f5a0c69f4ec',
    messagingSenderId: '992713183621',
    projectId: 'flutter-task-c28fb',
    authDomain: 'flutter-task-c28fb.firebaseapp.com',
    storageBucket: 'flutter-task-c28fb.appspot.com',
    measurementId: 'G-3HGY5P1ZXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdMnG_MHQHJiawIRyyxQpIuFRSpYk05w',
    appId: '1:992713183621:android:3ed98dd921f8114369f4ec',
    messagingSenderId: '992713183621',
    projectId: 'flutter-task-c28fb',
    storageBucket: 'flutter-task-c28fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTB4EwKDWrTIr5OzBKG1l0jR64WmimFUE',
    appId: '1:992713183621:ios:76ba482f624f869f69f4ec',
    messagingSenderId: '992713183621',
    projectId: 'flutter-task-c28fb',
    storageBucket: 'flutter-task-c28fb.appspot.com',
    iosClientId: '992713183621-ri722had71e1nm8gpgj8u10rokan114c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );
}
